source "https://rubygems.org"

gem "compass", ">=1.0.3"
gem "sassy-buttons", ">=0.2.6"
gem "breakpoint", ">=2.5.0"
gem "compass-rgbapng", ">=0.2.1"
gem "compass-normalize"
gem "autoprefixer-rails"
gem "guard"
gem "guard-livereload"
gem "guard-compass"
gem "modernizr-mixin"