source "https://rubygems.org"

gem "sass-globbing", ">=1.1.1"
gem "compass", ">=1.0.3"
gem "breakpoint", ">=2.5.0"
gem "compass-rgbapng", ">=0.2.1"
gem "compass-normalize"
gem "autoprefixer-rails"
gem "guard"
gem "guard-livereload"
gem "guard-compass"
gem "modernizr-mixin"