<?php

$plugin = array(
  'title'       => t('Two columns (equal) with top and bottom rows'),
  'category'    => t('Bear Skin responsive panel layouts'),
  'icon'        => 'icon.png',
  'css' => 'two_columns_top_and_bottom_rows.css',
  'theme'       => 'two-columns-top-and-bottom-rows',

  'regions'     => array(
    'top' => t('Top Row'),
    'left' => t('Left Column'),
    'right' => t('Right Column'),
    'bottom' => t('Bottom Row')
  )
);


