<?php

$plugin = array(
  'title'       => t('One column with top and bottom rows'),
  'category'    => t('Bear Skin responsive panel layouts'),
  'icon'        => 'icon.png',
  'css' => 'one_column_top_and_bottom_rows.css',
  'theme'       => 'one-column-top-and-bottom-rows',

  'regions'     => array(
    'top' => t('Top Row'),
    'center' => t('Center Column'),
    'bottom' => t('Bottom Row')
  )
);


